var title = new Vue({
    el:"#background",
    data:{
        num:"1",
        article:[
            {name:"aaa",content:"啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊"},
            {name:"bbb",content:"不啵啵啵啵啵啵啵啵啵啵啵啵啵啵啵啵啵啵不啵啵啵啵啵啵啵啵啵啵啵啵啵啵啵啵啵啵不啵啵啵啵啵啵啵啵啵啵啵啵啵啵啵啵啵啵"},
            {name:"ccc",content:"踩踩踩踩踩踩踩踩踩踩踩踩踩踩踩踩踩踩从踩踩踩踩踩踩踩踩踩踩踩踩踩踩踩踩踩踩从踩踩踩踩踩踩踩踩踩踩踩踩踩踩踩踩踩踩从"}            
        ],
        meeting:[
            {name:"no.1",content:"一一一一一语言一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一"},
            {name:"no.2",content:"一一一一一语言一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一"},
            {name:"no.3",content:"一一一一一语言一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一"},
            {name:"no.4",content:"一一一一一语言一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一"},
                
        ],
        research:"",
        course:[
            {name:"信息管理系统",
            lesson:[
                {date:"第一周第一节",feedback:["y","n","y","n"]},
                {date:"第一周第二节",feedback:["n","n","y","n"]},
                {date:"第一周第三节",feedback:["y","y","y","n"]},
                {date:"第一周第四节",feedback:["n","y","y","n"]},
            ],
            feedback:["1","2","3","4"],},
            {name:"创新创业",
            lesson:[
                {date:"第一周第一节",feedback:["y","n","y","n"]},
                {date:"第一周第二节",feedback:["n","n","y","n"]},
                {date:"第一周第三节",feedback:["y","y","y","n"]},
                {date:"第一周第四节",feedback:["n","y","y","n"]},
            ],
            feedback:["1","2","3","4"],}
        ],
    },
    methods:{
        checked:function(k){
            this.num = k;
        },
    }
})